version: '3'
services:
  db:
    image: postgres:13
    container_name: pfe-database
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pfe-network

  mailhog:
    image: mailhog/mailhog
    container_name: pfe-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - pfe-network

networks:
  pfe-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local