version: '3'
services:
  db:
    image: mysql:8.0
    container_name: pfe-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - pfe-mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pfe-network

  mailhog:
    image: mailhog/mailhog
    container_name: pfe-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - pfe-network

networks:
  pfe-network:
    driver: bridge

volumes:
  pfe-mysql-data:
    driver: local